// <auto-generated />
using System;
using MAVAppBackend;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MAVAppBackend.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20190223143008_normalizedname")]
    partial class normalizedname
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MAVAppBackend.Entities.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ExpiryDate");

                    b.Property<bool>("FullKnowledge");

                    b.Property<double?>("Latitude");

                    b.Property<double?>("Longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("MAVAppBackend.Entities.Train", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EncodedPolyline");

                    b.Property<DateTime>("ExpiryDate");

                    b.Property<int?>("FromId");

                    b.Property<bool>("FullKnowledge");

                    b.Property<string>("Name")
                        .HasMaxLength(255);

                    b.Property<int?>("ToId");

                    b.Property<int>("TrainNumber");

                    b.Property<int?>("Type");

                    b.Property<string>("ViszNumber")
                        .HasMaxLength(16);

                    b.HasKey("Id");

                    b.HasIndex("FromId");

                    b.HasIndex("ToId");

                    b.HasIndex("TrainNumber")
                        .IsUnique();

                    b.ToTable("Trains");
                });

            modelBuilder.Entity("MAVAppBackend.Entities.TrainInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Delay");

                    b.Property<string>("ElviraId")
                        .IsRequired()
                        .HasMaxLength(16);

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<int>("State");

                    b.Property<int>("TrainId");

                    b.HasKey("Id");

                    b.HasIndex("ElviraId")
                        .IsUnique();

                    b.HasIndex("TrainId");

                    b.ToTable("TrainInstances");
                });

            modelBuilder.Entity("MAVAppBackend.Entities.TrainStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<TimeSpan?>("Arrival");

                    b.Property<TimeSpan?>("Departure");

                    b.Property<double?>("Distance");

                    b.Property<int?>("IntDistance");

                    b.Property<string>("Platform")
                        .HasMaxLength(16);

                    b.Property<int>("StationId");

                    b.Property<int>("TrainId");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.HasIndex("TrainId", "StationId")
                        .IsUnique();

                    b.ToTable("TrainStations");
                });

            modelBuilder.Entity("MAVAppBackend.Entities.TrainStationLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("FromId");

                    b.Property<int?>("ToId");

                    b.Property<int>("TrainId");

                    b.HasKey("Id");

                    b.HasIndex("FromId");

                    b.HasIndex("ToId");

                    b.HasIndex("TrainId");

                    b.ToTable("TrainStationLinks");
                });

            modelBuilder.Entity("MAVAppBackend.Entities.Train", b =>
                {
                    b.HasOne("MAVAppBackend.Entities.Station", "From")
                        .WithMany()
                        .HasForeignKey("FromId");

                    b.HasOne("MAVAppBackend.Entities.Station", "To")
                        .WithMany()
                        .HasForeignKey("ToId");
                });

            modelBuilder.Entity("MAVAppBackend.Entities.TrainInstance", b =>
                {
                    b.HasOne("MAVAppBackend.Entities.Train", "Train")
                        .WithMany()
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MAVAppBackend.Entities.TrainStation", b =>
                {
                    b.HasOne("MAVAppBackend.Entities.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MAVAppBackend.Entities.Train", "Train")
                        .WithMany()
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MAVAppBackend.Entities.TrainStationLink", b =>
                {
                    b.HasOne("MAVAppBackend.Entities.Station", "From")
                        .WithMany()
                        .HasForeignKey("FromId");

                    b.HasOne("MAVAppBackend.Entities.Station", "To")
                        .WithMany()
                        .HasForeignKey("ToId");

                    b.HasOne("MAVAppBackend.Entities.Train", "Train")
                        .WithMany()
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
